export default [
    {
        key: "Total A",
        type: "area",
        values: [
            { axis: "Statement 1", group: "Group 1", value: 20 },
            { axis: "Statement 2", group: "Group 1", value: 22 },
            { axis: "Statement 3", group: "Group 1", value: 23 },
            { axis: "Statement 4", group: "Group 1", value: 21 },
            { axis: "Statement 5", group: "Group 2", value: 22 },
            { axis: "Statement 6", group: "Group 2", value: 19 },
            { axis: "Statement 7", group: "Group 3", value: 20 },
            { axis: "Statement 8", group: "Group 3", value: 23 },
            { axis: "Statement 9", group: "Group 3", value: 25 },
            { axis: "Statement 10", group: "Group 4", value: 26 },
            { axis: "Statement 11", group: "Group 4", value: 24 },
            { axis: "Statement 12", group: "Group 5", value: 22 },
            { axis: "Statement 13", group: "Group 5", value: 19 },
            { axis: "Statement 14", group: "Group 5", value: 18 },
            { axis: "Statement 15", group: "Group 5", value: 20 },
            { axis: "Statement 16", group: "Group 5", value: 22 },
            { axis: "Statement 17", group: "Group 6", value: 23 },
            { axis: "Statement 18", group: "Group 6", value: 26 },
            { axis: "Statement 19", group: "Group 6", value: 24 },
            { axis: "Statement 20", group: "Group 6", value: 22 },
            { axis: "Statement 21", group: "Group 6", value: 19 },
            { axis: "Statement 22", group: "Group 1", value: 24 },
            { axis: "Statement 23", group: "Group 1", value: 27 },
            { axis: "Statement 24", group: "Group 1", value: 25 }
        ]
    },

    {
        key: "Total B",
        type: "area",
        values: [
            { axis: "Statement 1", group: "Group 1", value: 18 },
            { axis: "Statement 2", group: "Group 1", value: 16 },
            { axis: "Statement 3", group: "Group 1", value: 15 },
            { axis: "Statement 4", group: "Group 1", value: 19 },
            { axis: "Statement 5", group: "Group 2", value: 20 },
            { axis: "Statement 6", group: "Group 2", value: 21 },
            { axis: "Statement 7", group: "Group 3", value: 22 },
            { axis: "Statement 8", group: "Group 3", value: 26 },
            { axis: "Statement 9", group: "Group 3", value: 25 },
            { axis: "Statement 10", group: "Group 4", value: 24 },
            { axis: "Statement 11", group: "Group 4", value: 23 },
            { axis: "Statement 12", group: "Group 5", value: 21 },
            { axis: "Statement 13", group: "Group 5", value: 20 },
            { axis: "Statement 14", group: "Group 5", value: 20 },
            { axis: "Statement 15", group: "Group 5", value: 18 },
            { axis: "Statement 16", group: "Group 5", value: 16 },
            { axis: "Statement 17", group: "Group 6", value: 18 },
            { axis: "Statement 18", group: "Group 6", value: 18 },
            { axis: "Statement 19", group: "Group 6", value: 22 },
            { axis: "Statement 20", group: "Group 6", value: 21 },
            { axis: "Statement 21", group: "Group 6", value: 19 },
            { axis: "Statement 22", group: "Group 1", value: 27 },
            { axis: "Statement 23", group: "Group 1", value: 25 },
            { axis: "Statement 24", group: "Group 1", value: 23 }
        ]
    },

    {
        key: "Best item",
        type: "dot",
        values: [
            { axis: "Statement 1", group: "Group 1", value: 35 },
            { axis: "Statement 2", group: "Group 1", value: 34 },
            { axis: "Statement 3", group: "Group 1", value: 33 },
            { axis: "Statement 4", group: "Group 1", value: 30 },
            { axis: "Statement 5", group: "Group 2", value: 31 },
            { axis: "Statement 6", group: "Group 2", value: 34 },
            { axis: "Statement 7", group: "Group 3", value: 32 },
            { axis: "Statement 8", group: "Group 3", value: 33 },
            { axis: "Statement 9", group: "Group 3", value: 35 },
            { axis: "Statement 10", group: "Group 4", value: 34 },
            { axis: "Statement 11", group: "Group 4", value: 31 },
            { axis: "Statement 12", group: "Group 5", value: 30 },
            { axis: "Statement 13", group: "Group 5", value: 32 },
            { axis: "Statement 14", group: "Group 5", value: 31 },
            { axis: "Statement 15", group: "Group 5", value: 31 },
            { axis: "Statement 16", group: "Group 5", value: 34 },
            { axis: "Statement 17", group: "Group 6", value: 32 },
            { axis: "Statement 18", group: "Group 6", value: 35 },
            { axis: "Statement 19", group: "Group 6", value: 35 },
            { axis: "Statement 20", group: "Group 6", value: 32 },
            { axis: "Statement 21", group: "Group 6", value: 33 },
            { axis: "Statement 22", group: "Group 1", value: 34 },
            { axis: "Statement 23", group: "Group 1", value: 35 },
            { axis: "Statement 24", group: "Group 1", value: 32 }
        ]
    },

    {
        key: "Item 1",
        type: "line",
        values: [
            { axis: "Statement 1", group: "Group 1", value: 22 },
            { axis: "Statement 2", group: "Group 1", value: 23 },
            { axis: "Statement 3", group: "Group 1", value: 25 },
            { axis: "Statement 4", group: "Group 1", value: 26 },
            { axis: "Statement 5", group: "Group 2", value: 27 },
            { axis: "Statement 6", group: "Group 2", value: 25 },
            { axis: "Statement 7", group: "Group 3", value: 23 },
            { axis: "Statement 8", group: "Group 3", value: 21 },
            { axis: "Statement 9", group: "Group 3", value: 19 },
            { axis: "Statement 10", group: "Group 4", value: 18 },
            { axis: "Statement 11", group: "Group 4", value: 19 },
            { axis: "Statement 12", group: "Group 5", value: 20 },
            { axis: "Statement 13", group: "Group 5", value: 23 },
            { axis: "Statement 14", group: "Group 5", value: 22 },
            { axis: "Statement 15", group: "Group 5", value: 21 },
            { axis: "Statement 16", group: "Group 5", value: 21 },
            { axis: "Statement 17", group: "Group 6", value: 23 },
            { axis: "Statement 18", group: "Group 6", value: 24 },
            { axis: "Statement 19", group: "Group 6", value: 22 },
            { axis: "Statement 20", group: "Group 6", value: 21 },
            { axis: "Statement 21", group: "Group 6", value: 21 },
            { axis: "Statement 22", group: "Group 1", value: 22 },
            { axis: "Statement 23", group: "Group 1", value: 23 },
            { axis: "Statement 24", group: "Group 1", value: 24 }
        ]
    },

    {
        key: "Item 2",
        type: "line",
        values: [
            { axis: "Statement 1", group: "Group 1", value: 28 },
            { axis: "Statement 2", group: "Group 1", value: 26 },
            { axis: "Statement 3", group: "Group 1", value: 27 },
            { axis: "Statement 4", group: "Group 1", value: 28 },
            { axis: "Statement 5", group: "Group 2", value: 26 },
            { axis: "Statement 6", group: "Group 2", value: 25 },
            { axis: "Statement 7", group: "Group 3", value: 28 },
            { axis: "Statement 8", group: "Group 3", value: 27 },
            { axis: "Statement 9", group: "Group 3", value: 26 },
            { axis: "Statement 10", group: "Group 4", value: 26 },
            { axis: "Statement 11", group: "Group 4", value: 28 },
            { axis: "Statement 12", group: "Group 5", value: 26 },
            { axis: "Statement 13", group: "Group 5", value: 25 },
            { axis: "Statement 14", group: "Group 5", value: 29 },
            { axis: "Statement 15", group: "Group 5", value: 28 },
            { axis: "Statement 16", group: "Group 5", value: 26 },
            { axis: "Statement 17", group: "Group 6", value: 27 },
            { axis: "Statement 18", group: "Group 6", value: 25 },
            { axis: "Statement 19", group: "Group 6", value: 26 },
            { axis: "Statement 20", group: "Group 6", value: 28 },
            { axis: "Statement 21", group: "Group 6", value: 25 },
            { axis: "Statement 22", group: "Group 1", value: 27 },
            { axis: "Statement 23", group: "Group 1", value: 26 },
            { axis: "Statement 24", group: "Group 1", value: 28 }
        ]
    }
];
